[package]
name = "m4-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
cml = { git = "https://github.com/juv4uk/cml.git", rev = "6ce577f24083c54b55bf1870396f6b3e1c3d04b9" }
wsm-os-target = { git = "https://github.com/juv4uk/wsm-target-contract.git", rev = "90fa2cf324d05d8a7baafcac620eb5360f05e5b3" }
sha2 = "0.10.8"
hex = "0.4.3"
serde_json = "1.0.122"
