[workspace]
members = [
    "crates/m4-generator",
    "crates/wsm-os-block",
    "crates/wsm-os-fs-adapter",
    "crates/wsm-os-hosted",
    "crates/wsm-os-image",
    "crates/wsm-os-runtime",
    "crates/wsm-os-target",
    "crates/wsm-os-kernel",
    "crates/wsm-os-fs-parser",
    "crates/wsm-os-virtio",
]
resolver = "2"
