; Generated by juv4uk/sens/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/sens)
    (branch main)
    (path language-contract.lisp))
  (revision "04058d2d0b69489a145539aff52fa3517ca4d82c")
  (sha256 "177d532d24c1f0738a934152f65c7f01f90b5593c8dbfe519e31148c0aa80c40"))
