; Generated by juv4uk/my-lisp/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/my-lisp)
    (branch main)
    (path language-contract.lisp))
  (revision "fa42bdb69739712588702a091e352a9f7f692929")
  (sha256 "d031a9835b77a3453be5fbd7c4336b509329e3e5bf44834954931a68850310e3"))
