; Generated by juv4uk/my-lisp/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/my-lisp)
    (branch main)
    (path language-contract.lisp))
  (revision "fae8d8f8ea6713d94db1f1fd7e8df4398279317e")
  (sha256 "ab9b1a852b5877fd3df0b8373902b4c363bc1138fe1f15a4361db674af5d0969"))
