; Generated by juv4uk/my-lisp/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/my-lisp)
    (branch main)
    (path language-contract.my))
  (revision "bd390e5db34920ada5ecb909fc5e1776c43f63df")
  (sha256 "737cc3373abca40ae511ea0114609fdcb7a172b918e69dced615a458ff5818a9"))
