#!/usr/bin/env bash
# Verify that committed fixture evidence was generated by the CML revision
# pinned in contracts/cml.lock. The ABI package is independently identified by
# target_contract_digest in that manifest.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

CML_LOCK_SHA=$(grep -oP '(?<=\(cml-revision ")[0-9a-f]{40}(?="\))' \
    "$ROOT_DIR/contracts/cml.lock")
MANIFEST_SHA=$(grep -oP '(?<="cml_sha": ")[0-9a-f]{40}(?=")' \
    "$ROOT_DIR/artifacts/fixture-manifest.json" | head -1)

if [[ -z "$CML_LOCK_SHA" || -z "$MANIFEST_SHA" ]]; then
    echo "ERROR: could not read CML provenance from contracts/cml.lock or fixture manifest" >&2
    exit 1
fi

echo "contracts/cml.lock CML rev : $CML_LOCK_SHA"
echo "fixture manifest rev       : $MANIFEST_SHA"

if [[ "$CML_LOCK_SHA" != "$MANIFEST_SHA" ]]; then
    echo "FAIL: fixture evidence was not generated by the pinned CML revision" >&2
    exit 1
fi

echo "OK: fixture CML provenance is consistent ($CML_LOCK_SHA)"
