#!/usr/bin/env bash
# Verify that committed fixture evidence was generated by the CML revision
# requested by m4-generator. The ABI package is independently identified by
# target_contract_digest in that manifest.
set -euo pipefail

M4_SHA=$(grep -oP '(?<=cml = \{ git = "https://github.com/juv4uk/cml.git", rev = ")[0-9a-f]{40}(?=" \})' \
    crates/m4-generator/Cargo.toml)
GENERATOR_SHA=$(grep -oP '(?<=const CML_REVISION: &str = ")[0-9a-f]{40}(?=";)' \
    crates/m4-generator/src/main.rs)
MANIFEST_SHA=$(grep -oP '(?<="cml_sha": ")[0-9a-f]{40}(?=")' \
    artifacts/fixture-manifest.json | head -1)

if [[ -z "$M4_SHA" || -z "$GENERATOR_SHA" || -z "$MANIFEST_SHA" ]]; then
    echo "ERROR: could not read CML provenance from generator or fixture manifest" >&2
    exit 1
fi

echo "m4-generator CML rev: $M4_SHA"
echo "generator constant  : $GENERATOR_SHA"
echo "fixture manifest rev : $MANIFEST_SHA"

if [[ "$M4_SHA" != "$GENERATOR_SHA" || "$M4_SHA" != "$MANIFEST_SHA" ]]; then
    echo "FAIL: fixture evidence was not generated by the pinned CML revision" >&2
    exit 1
fi

echo "OK: fixture CML provenance is consistent ($M4_SHA)"
