[package]
name = "wsm-os-hosted"
version = "0.1.0"
edition = "2024"
description = "Hosted evidence harness for the wsm-os runtime ABI"
publish = false
build = "build.rs"

[dependencies]
wsm-os-runtime = { path = "../wsm-os-runtime" }
wsm-os-target = { git = "https://github.com/juv4uk/wsm-target-contract.git", rev = "90fa2cf324d05d8a7baafcac620eb5360f05e5b3" }
