#![no_std]
#![no_main]

use bootloader_api::config::Mapping;
use bootloader_api::{BootloaderConfig, entry_point, BootInfo};

pub static BOOTLOADER_CONFIG: BootloaderConfig = {
    let mut config = BootloaderConfig::new_default();
    config.mappings.physical_memory = Some(Mapping::Dynamic);
    config
};

entry_point!(kernel_main, config = &BOOTLOADER_CONFIG);
use core::arch::asm;
use core::mem::MaybeUninit;
use core::panic::PanicInfo;
use wsm_os_runtime::{wsm_fail, ConsCell, RuntimeContext};
use wsm_os_target::{decode_symbol, ClosureDescriptor, Word};

mod fs_records;
mod guest_block;


fn kernel_main(boot_info: &'static mut BootInfo) -> ! {
    // Store the physical-memory offset provided by the bootloader so that
    // MMIO physical addresses (from PCI BARs) can be translated to virtual
    // addresses accessible under the kernel's page tables.
    unsafe {
        PHYS_MEM_OFFSET = boot_info
            .physical_memory_offset
            .into_option()
            .unwrap_or(0);
    }
    serial_init();
    serial_write(b"WSM-OS BOOT schema=1 arch=x86_64 status=ok\n");

    let heap = core::ptr::addr_of_mut!(HEAP).cast::<MaybeUninit<ConsCell>>();
    let closures = core::ptr::addr_of_mut!(CLOSURES).cast::<MaybeUninit<ClosureDescriptor>>();
    // SAFETY: HEAP is a private, aligned, fixed-size arena used only by this
    // single-threaded boot witness for the lifetime of the context.
    let mut context = unsafe {
        RuntimeContext::new_with_closures(
            heap,
            HEAP_CAPACITY,
            closures,
            CLOSURE_CAPACITY,
            kernel_failure,
        )
    };
    // SAFETY: fixture.o is generated by the pinned CML revision, its committed
    // manifest exports exactly wsm_entry and admits only the wsm_* ABI imports.
    let result = unsafe { wsm_entry(&mut context) };

    let fixture_name = option_env!("WSM_FIXTURE").unwrap_or("fixture");
    if fixture_name == "fs-fixture" {
        if fs_fixture_witness(&mut context) {
            serial_write(
                b"WSM-OS FS schema=1 format=wsm-fs-records value=(hello world) status=ok\n",
            );
            serial_write(b"WSM-OS BLOCK schema=1 medium=guest-memory block=0 read=ok write=ok flush=ok status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS FS schema=1 error=invalid-record status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "repl-fixture" {
        repl_fixture();
    } else if fixture_name == "m5a-fixture" {
        if is_m5a_fixture_result(result, &context) {
            serial_write(b"WSM-OS RESULT schema=1 value=(40 . t) status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m5b-success-fixture" {
        if is_m5b_success_fixture_result(result, &context) {
            serial_write(b"WSM-OS RESULT schema=1 value=(1152921504606846975 . -1152921504606846976) status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m5b-overflow-fixture" {
        // We shouldn't reach here because wsm_fail triggers a kernel_failure trap.
        serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
        qemu_exit(0x12)
    } else if fixture_name == "m5c-tail-call-fixture" {
        if result == wsm_os_target::TRUE {
            serial_write(b"WSM-OS RESULT schema=1 value=t status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m1-identity-lambda-fixture" {
        if result == wsm_os_target::encode_fixnum(7).unwrap() {
            serial_write(b"WSM-OS RESULT schema=1 value=7 execution=machine-call status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m1-lexical-lambda-fixture" {
        if is_m1_lexical_lambda_result(result, &context) {
            serial_write(b"WSM-OS RESULT schema=1 value=(A) execution=lexical-frame status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m1-captured-lambda-fixture" {
        if is_m1_captured_lambda_result(result, &context) {
            serial_write(
                b"WSM-OS RESULT schema=1 value=(A B) execution=captured-frame status=ok\n",
            );
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "m2-escaping-closure-fixture" {
        if is_m1_captured_lambda_result(result, &context) {
            serial_write(
                b"WSM-OS RESULT schema=1 value=(A B) execution=escaping-closure status=ok\n",
            );
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    } else if fixture_name == "d0-virtio-identity-fixture" {
        if result == wsm_os_target::CANONICAL_T || result == wsm_os_target::TRUE {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=identity value=t execution=wsm status=ok\n",
            );
            qemu_exit(0x10)
        } else {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=identity error=unexpected-value status=error\n",
            );
            qemu_exit(0x12)
        }
    } else if fixture_name == "d1-pci-config-capability-fixture" {
        if result == wsm_os_target::CANONICAL_T || result == wsm_os_target::TRUE {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=pci-config value=t execution=wsm status=ok\n",
            );
            qemu_exit(0x10)
        } else {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=pci-config error=unexpected-value status=error\n",
            );
            qemu_exit(0x12)
        }
    } else if fixture_name == "d1-pci-config-bounds-fixture" {
        // A bounded capability violation must have trapped through wsm_fail.
        serial_write(b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=pci-config error=missing-condition status=error\n");
        qemu_exit(0x12)
    } else if fixture_name == "d2-virtio-blk-status-fixture" {
        if result == wsm_os_target::CANONICAL_T || result == wsm_os_target::TRUE {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=mmio-status value=t execution=wsm status=ok\n",
            );
            qemu_exit(0x10)
        } else {
            serial_write(
                b"WSM-OS DRIVER schema=1 driver=virtio-blk stage=mmio-status error=unexpected-value status=error\n",
            );
            qemu_exit(0x12)
        }
    } else {
        if is_first_fixture_result(result, &context) {
            serial_write(b"WSM-OS RESULT schema=1 value=(A . B) status=ok\n");
            qemu_exit(0x10)
        } else {
            serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
            qemu_exit(0x12)
        }
    }
}

const FS_RECORDS: &[u8] = include_bytes!("../../../artifacts/fs-qemu-records.txt");

fn fs_fixture_witness(context: &mut RuntimeContext) -> bool {
    let mut medium = guest_block::GuestBlockMedium::new();
    if !medium.write(FS_RECORDS) || !medium.read_matches(FS_RECORDS) || !medium.flush() {
        return false;
    }
    let Ok(stream) = fs_records::parse(FS_RECORDS) else {
        return false;
    };
    if fs_records::reconstruct_root(&stream).is_err() {
        return false;
    }
    if stream.count != 3
        || stream.records[0].map(|record| record.kind) != Some(fs_records::RecordKind::Root)
        || stream.records[1].map(|record| record.kind) != Some(fs_records::RecordKind::Object)
    {
        return false;
    }
    let hello = wsm_os_target::encode_symbol(1).unwrap();
    let world = wsm_os_target::encode_symbol(2).unwrap();
    let Ok(tail) = context.cons(world, wsm_os_target::NIL) else {
        return false;
    };
    let Ok(root) = context.cons(hello, tail) else {
        return false;
    };
    let Ok(root_cell) = context.cell(root) else {
        return false;
    };
    let Ok(tail_cell) = context.cell(root_cell.cdr) else {
        return false;
    };
    decode_symbol(root_cell.car) == Some(1)
        && decode_symbol(tail_cell.car) == Some(2)
        && tail_cell.cdr == wsm_os_target::NIL
}

const HEAP_CAPACITY: usize = 8;
const CLOSURE_CAPACITY: usize = 4;
static mut HEAP: [MaybeUninit<ConsCell>; HEAP_CAPACITY] = [MaybeUninit::uninit(); HEAP_CAPACITY];
static mut CLOSURES: [MaybeUninit<ClosureDescriptor>; CLOSURE_CAPACITY] =
    [MaybeUninit::uninit(); CLOSURE_CAPACITY];

unsafe extern "C" {
    fn wsm_entry(context: *mut RuntimeContext) -> Word;
}

use wsm_os_target::{
    decode_capability_descriptor, encode_capability_descriptor, CapabilityDescriptor,
    CapabilityKind,
};

const PCI_CONFIG_CAPABILITY_ID: Word = 1;
const PCI_CONFIG_ADDRESS: u16 = 0xcf8;
const PCI_CONFIG_DATA: u16 = 0xcfc;

/// Active capability entry in the substrate registry.
#[derive(Clone, Copy)]
struct CapabilityGrant {
    kind: CapabilityKind,
    instance: u8,
    nonce: Word,
    active: bool,
}

const MAX_CAPABILITY_GRANTS: usize = 4;
static mut CAPABILITY_REGISTRY: [CapabilityGrant; MAX_CAPABILITY_GRANTS] = [CapabilityGrant {
    kind: CapabilityKind::PciConfig,
    instance: 0,
    nonce: 0,
    active: false,
}; MAX_CAPABILITY_GRANTS];

/// Physical memory offset from bootloader (virtual = PHYS_MEM_OFFSET + physical).
/// Zero means identity-mapping (physical == virtual), which is safe as a fallback.
static mut PHYS_MEM_OFFSET: u64 = 0;

/// Physical base address of the virtio-blk VirtIO common-config MMIO region.
/// Resolved once by walking the PCI capability list for BDF 00:05.0.
static mut MMIO_COMMON_CFG_PHYS: u64 = 0;

/// Hardware/boot-provisioned provenance nonce for PCI config capability.
/// Boot nonces are non-zero tokens verified by privileged gates (max 45 bits).
const PCI_CONFIG_BOOT_NONCE: Word = 0x1504_3495_4346; // 45-bit valid nonce

fn init_pci_config_grant() -> Word {
    unsafe {
        let registry = core::ptr::addr_of_mut!(CAPABILITY_REGISTRY);
        (*registry)[0] = CapabilityGrant {
            kind: CapabilityKind::PciConfig,
            instance: 0,
            nonce: PCI_CONFIG_BOOT_NONCE,
            active: true,
        };
    }
    let desc = CapabilityDescriptor::new(CapabilityKind::PciConfig, 0, PCI_CONFIG_BOOT_NONCE)
        .expect("PCI config descriptor must be valid");
    encode_capability_descriptor(desc).expect("PCI config capability must encode")
}

fn verify_capability_grant(capability: Word, expected_kind: CapabilityKind, expected_instance: u8) -> bool {
    // 1. Structural decode: must be a valid Capability tag and well-formed CapabilityDescriptor
    let Some(desc) = decode_capability_descriptor(capability) else {
        // Fallback for legacy ID 1 until all callers migrate
        if capability == wsm_os_target::encode_capability(PCI_CONFIG_CAPABILITY_ID).unwrap()
            && expected_kind == CapabilityKind::PciConfig
            && expected_instance == 0
        {
            return true;
        }
        return false;
    };

    // 2. Class and instance must match the requested operation
    if desc.kind != expected_kind || desc.instance != expected_instance {
        return false;
    }

    // 3. Provenance check: must match an active grant in the substrate registry
    unsafe {
        let registry = core::ptr::addr_of!(CAPABILITY_REGISTRY);
        for i in 0..MAX_CAPABILITY_GRANTS {
            let grant = &(*registry)[i];
            if grant.active
                && grant.kind == desc.kind
                && grant.instance == desc.instance
                && grant.nonce == desc.nonce
            {
                return true;
            }
        }
    }
    false
}

/// Boot-provisioned, read-only PCI segment-0/bus-0 capability for the first
/// driver witness. Device recognition remains in generated WSM.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wsm_pci_config_capability(context: *mut RuntimeContext) -> Word {
    if context.is_null() {
        loop {
            core::hint::spin_loop();
        }
    }
    init_pci_config_grant()
}

/// Perform one bounded PCI configuration mechanism-1 read. This function
/// knows ranges and privilege, not virtio identity or driver policy.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wsm_pci_config_read16(
    context: *mut RuntimeContext,
    capability: Word,
    bus: Word,
    device: Word,
    function: Word,
    offset: Word,
) -> Word {
    let (Some(0), Some(device), Some(function), Some(offset)) = (
        wsm_os_target::decode_fixnum(bus),
        wsm_os_target::decode_fixnum(device),
        wsm_os_target::decode_fixnum(function),
        wsm_os_target::decode_fixnum(offset),
    ) else {
        unsafe {
            wsm_fail(
                context,
                wsm_os_target::ErrorCode::AbiViolation as u32,
                capability,
                0x5043_4902,
            )
        }
    };
    if !verify_capability_grant(capability, CapabilityKind::PciConfig, 0)
        || !(0..=31).contains(&device)
        || !(0..=7).contains(&function)
        || !(0..=254).contains(&offset)
        || offset % 2 != 0
    {
        unsafe {
            wsm_fail(
                context,
                wsm_os_target::ErrorCode::AbiViolation as u32,
                capability,
                0x5043_4903,
            )
        }
    }
    let address = 0x8000_0000_u32
        | ((device as u32) << 11)
        | ((function as u32) << 8)
        | ((offset as u32) & 0xfc);
    unsafe { outl(PCI_CONFIG_ADDRESS, address) };
    let value = unsafe { inl(PCI_CONFIG_DATA) };
    let shift = ((offset as u32) & 2) * 8;
    match wsm_os_target::encode_fixnum(((value >> shift) & 0xffff) as i64) {
        Some(value) => value,
        None => unsafe {
            wsm_fail(
                context,
                wsm_os_target::ErrorCode::AbiViolation as u32,
                capability,
                0x5043_4904,
            )
        },
    }
}

// ---------------------------------------------------------------------------
// MMIO substrate — VirtIO common-config discovery and bounded register access
// ---------------------------------------------------------------------------

/// Raw 32-bit PCI config read (mechanism only; not exposed to WSM).
fn raw_pci_read32(dev: u32, offset: u32) -> u32 {
    let address = 0x8000_0000_u32 | (dev << 11) | (offset & 0xFC);
    unsafe { outl(PCI_CONFIG_ADDRESS, address) };
    unsafe { inl(PCI_CONFIG_DATA) }
}

/// Resolve the physical base address of a PCI BAR (supports 32-bit and 64-bit).
fn raw_bar_phys(dev: u32, bar_num: u8) -> u64 {
    let bar_offset = 0x10 + (bar_num as u32) * 4;
    let bar_low = raw_pci_read32(dev, bar_offset);
    if bar_low & 0x01 != 0 {
        return 0; // I/O BAR — skip
    }
    let base_low = (bar_low & 0xFFFF_FFF0) as u64;
    let is_64bit = ((bar_low >> 1) & 0x3) == 2;
    if is_64bit {
        let bar_high = raw_pci_read32(dev, bar_offset + 4);
        base_low | ((bar_high as u64) << 32)
    } else {
        base_low
    }
}

/// Walk the VirtIO PCI capability list for BDF 00:05.0 to find the
/// COMMON_CFG region (cfg_type = 1) and cache its physical address.
/// Substrate mechanism; never called from WSM.
fn init_mmio_common_cfg() {
    const VIRTIO_DEV: u32 = 5; // BDF 00:05.0

    // PCI status register bit 4: Capabilities List present
    let cmd_status = raw_pci_read32(VIRTIO_DEV, 0x04);
    if (cmd_status >> 16) as u16 & 0x10 == 0 {
        return; // no capability list
    }

    // Capabilities pointer is at PCI config offset 0x34 (byte 0 of the dword)
    let cap_ptr_raw = raw_pci_read32(VIRTIO_DEV, 0x34);
    let mut cap_offset = (cap_ptr_raw & 0xFC) as u32;

    let mut iters = 0_u32;
    while cap_offset >= 0x40 && cap_offset < 0x100 && iters < 32 {
        iters += 1;

        // Dword at cap_offset:
        //   byte 0 = cap_id
        //   byte 1 = cap_next
        //   byte 2 = cap_len
        //   byte 3 = cfg_type  (VirtIO-specific)
        let dw0 = raw_pci_read32(VIRTIO_DEV, cap_offset);
        let cap_id = (dw0 & 0xFF) as u8;
        let cap_next = ((dw0 >> 8) & 0xFC) as u32;
        let cfg_type = (dw0 >> 24) as u8;

        if cap_id == 0x09 && cfg_type == 1 {
            // VIRTIO_PCI_CAP_COMMON_CFG: byte 4 = bar, bytes 8-11 = offset_in_bar
            let dw1 = raw_pci_read32(VIRTIO_DEV, cap_offset + 4);
            let bar_num = (dw1 & 0xFF) as u8;
            let offset_in_bar = raw_pci_read32(VIRTIO_DEV, cap_offset + 8);
            let bar_phys = raw_bar_phys(VIRTIO_DEV, bar_num);
            if bar_phys != 0 {
                unsafe {
                    MMIO_COMMON_CFG_PHYS = bar_phys + offset_in_bar as u64;
                }
                return;
            }
        }

        if cap_next == 0 {
            break;
        }
        cap_offset = cap_next;
    }

    // Fallback: try BAR4 directly (QEMU modern virtio-blk typical layout)
    let fallback = raw_bar_phys(VIRTIO_DEV, 4);
    if fallback != 0 {
        unsafe { MMIO_COMMON_CFG_PHYS = fallback; }
    }
}

/// Boot nonce for MMIO capability (45-bit valid range).
const MMIO_BOOT_NONCE: Word = 0x1A04_9512_4347; // 45-bit valid nonce (max 0x1FFF_FFFF_FFFF)

fn init_mmio_grant() -> Word {
    init_mmio_common_cfg();
    unsafe {
        let registry = core::ptr::addr_of_mut!(CAPABILITY_REGISTRY);
        (*registry)[1] = CapabilityGrant {
            kind: CapabilityKind::Mmio,
            instance: 0,
            nonce: MMIO_BOOT_NONCE,
            active: true,
        };
    }
    let desc = CapabilityDescriptor::new(CapabilityKind::Mmio, 0, MMIO_BOOT_NONCE)
        .expect("MMIO descriptor must be valid");
    encode_capability_descriptor(desc).expect("MMIO capability must encode")
}

/// Provision an MMIO capability for the virtio-blk common-config region.
/// Mechanism: reads BAR4 from PCI config, caches physical address.
/// Policy (which registers to access) stays in WSM.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wsm_mmio_capability(context: *mut RuntimeContext) -> Word {
    if context.is_null() {
        loop {
            core::hint::spin_loop();
        }
    }
    init_mmio_grant()
}

/// Bounded 32-bit MMIO register read. Offset is a non-negative fixnum
/// (byte offset within the common-config region, max 4095).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wsm_mmio_read32(
    context: *mut RuntimeContext,
    capability: Word,
    offset: Word,
) -> Word {
    let Some(offset) = wsm_os_target::decode_fixnum(offset) else {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F01) }
    };
    if !verify_capability_grant(capability, CapabilityKind::Mmio, 0)
        || !(0..=4095).contains(&offset)
        || offset % 4 != 0
    {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F02) }
    }
    let phys_base = unsafe { MMIO_COMMON_CFG_PHYS };
    if phys_base == 0 {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F03) }
    }
    let virt_addr = unsafe { PHYS_MEM_OFFSET } + phys_base + offset as u64;
    // SAFETY: capability verified, offset bounded, address resolved from bootloader mapping
    let value = unsafe { (virt_addr as *const u32).read_volatile() };
    wsm_os_target::encode_fixnum(value as i64).expect("32-bit MMIO read must fit in fixnum")
}

/// Bounded 32-bit MMIO register write. Offset and value are non-negative fixnums.
/// Returns NIL on success.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn wsm_mmio_write32(
    context: *mut RuntimeContext,
    capability: Word,
    offset: Word,
    value: Word,
) -> Word {
    let (Some(offset), Some(value)) = (
        wsm_os_target::decode_fixnum(offset),
        wsm_os_target::decode_fixnum(value),
    ) else {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F04) }
    };
    if !verify_capability_grant(capability, CapabilityKind::Mmio, 0)
        || !(0..=4095).contains(&offset)
        || offset % 4 != 0
    {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F05) }
    }
    let phys_base = unsafe { MMIO_COMMON_CFG_PHYS };
    if phys_base == 0 {
        unsafe { wsm_fail(context, wsm_os_target::ErrorCode::AbiViolation as u32, capability, 0x4D494F06) }
    }
    let virt_addr = unsafe { PHYS_MEM_OFFSET } + phys_base + offset as u64;
    // SAFETY: capability verified, offset bounded, address resolved from bootloader mapping
    unsafe { (virt_addr as *mut u32).write_volatile(value as u32) };
    wsm_os_target::NIL
}

extern "C" fn kernel_failure(context_ptr: *const RuntimeContext, _code: u32) -> ! {
    let ctx = unsafe { &*context_ptr };
    let kind_bytes: &[u8] = match ctx.condition.kind {
        1 => b"OOM",
        2 => b"TYPE",
        3 => b"SYMBOL",
        4 => b"ABI",
        _ => b"UNKNOWN",
    };
    serial_write(b"WSM-OS CONDITION schema=1 kind=");
    serial_write(kind_bytes);
    serial_write(b" source=");
    serial_write_decimal(ctx.condition.source_id);
    serial_write(b" value=");
    serial_write_word(ctx.condition.offending_value);
    serial_write(b"\n");
    qemu_exit(0x12)
}

fn serial_write_word(mut value: Word) {
    let mut digits = [0_u8; 20];
    let mut cursor = digits.len();
    if value == 0 {
        serial_write(b"0");
        return;
    }
    while value != 0 && cursor > 0 {
        cursor -= 1;
        unsafe {
            *digits.get_unchecked_mut(cursor) = b'0' + (value % 10) as u8;
        }
        value /= 10;
    }
    serial_write(unsafe {
        core::slice::from_raw_parts(digits.as_ptr().add(cursor), digits.len() - cursor)
    });
}

fn is_first_fixture_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(cell) = context.cell(value) else {
        return false;
    };
    decode_symbol(cell.car) == Some(1) && decode_symbol(cell.cdr) == Some(2)
}

fn is_m1_lexical_lambda_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(cell) = context.cell(value) else {
        return false;
    };
    decode_symbol(cell.car) == Some(1) && cell.cdr == wsm_os_target::NIL
}

fn is_m1_captured_lambda_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(first) = context.cell(value) else {
        return false;
    };
    let Ok(second) = context.cell(first.cdr) else {
        return false;
    };
    decode_symbol(first.car) == Some(1)
        && decode_symbol(second.car) == Some(2)
        && second.cdr == wsm_os_target::NIL
}

fn is_m5a_fixture_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(cell) = context.cell(value) else {
        return false;
    };
    wsm_os_target::decode_fixnum(cell.car) == Some(40)
        && (cell.cdr == wsm_os_target::CANONICAL_T || cell.cdr == wsm_os_target::TRUE)
}

fn is_m5b_success_fixture_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(cell) = context.cell(value) else {
        return false;
    };
    wsm_os_target::decode_fixnum(cell.car) == Some(wsm_os_target::FIXNUM_MAX)
        && wsm_os_target::decode_fixnum(cell.cdr) == Some(wsm_os_target::FIXNUM_MIN)
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    serial_init();
    serial_write(b"WSM-OS PANIC schema=1 arch=x86_64 status=panic\n");
    qemu_exit(0x11)
}

const COM1: u16 = 0x3f8;

fn serial_init() {
    unsafe {
        outb(COM1 + 1, 0x00);
        outb(COM1 + 3, 0x80);
        outb(COM1, 0x03);
        outb(COM1 + 1, 0x00);
        outb(COM1 + 3, 0x03);
        outb(COM1 + 2, 0xc7);
        outb(COM1 + 4, 0x0b);
    }
}

fn serial_write(bytes: &[u8]) {
    for &byte in bytes {
        unsafe { outb(COM1, byte) };
    }
}

fn repl_fixture() -> ! {
    serial_write(b"WSM-OS REPL schema=1 status=ready\n> ");
    let mut line = [0_u8; 64];
    let mut len: usize = 0;
    loop {
        if !serial_has_input() {
            core::hint::spin_loop();
            continue;
        }
        let byte = unsafe { inb(COM1) };
        if byte == b'\r' || byte == b'\n' {
            serial_write(b"\n");
            let input = trim_whitespace(&line[..len]);
            if input.len() == 1 && input[0] == b'q' {
                serial_write(b"WSM-OS REPL status=bye\n");
                qemu_exit(0x10)
            } else if input.len() == 1 && input[0] == b'h' {
                serial_write(b"commands: h=help q=quit <fixnum> nil t\n> ");
            } else if bytes_eq(input, b"nil") {
                serial_write(b"WSM-OS REPL value=nil\n> ");
            } else if bytes_eq(input, b"t") {
                serial_write(b"WSM-OS REPL value=t\n> ");
            } else if let Some(n) = parse_i64(input) {
                if let Some(_word) = wsm_os_target::encode_fixnum(n) {
                    serial_write(b"WSM-OS REPL value=");
                    serial_write_signed_decimal(n);
                    serial_write(b"\n> ");
                } else {
                    serial_write(b"WSM-OS CONDITION schema=1 kind=NUMERIC_OVERFLOW source=repl value=");
                    serial_write(input);
                    serial_write(b"\n> ");
                }
            } else if !input.is_empty() {
                serial_write(b"WSM-OS CONDITION schema=1 kind=TYPE source=repl value=");
                serial_write(input);
                serial_write(b"\n> ");
            } else {
                serial_write(b"> ");
            }
            len = 0;
        } else if byte == 8 || byte == 127 {
            len = len.saturating_sub(1);
        } else if len < line.len() {
            line[len] = byte;
            len += 1;
            serial_write(&[byte]);
        }
    }
}

fn trim_whitespace(mut slice: &[u8]) -> &[u8] {
    while let Some((&first, rest)) = slice.split_first() {
        if first == b' ' || first == b'\t' {
            slice = rest;
        } else {
            break;
        }
    }
    while let Some((&last, rest)) = slice.split_last() {
        if last == b' ' || last == b'\t' {
            slice = rest;
        } else {
            break;
        }
    }
    slice
}

fn parse_i64(bytes: &[u8]) -> Option<i64> {
    if bytes.is_empty() {
        return None;
    }
    let (is_negative, digits) = match bytes[0] {
        b'-' => (true, &bytes[1..]),
        b'+' => (false, &bytes[1..]),
        _ => (false, bytes),
    };
    if digits.is_empty() {
        return None;
    }
    let mut acc: i64 = 0;
    for &b in digits {
        if !b.is_ascii_digit() {
            return None;
        }
        let digit = (b - b'0') as i64;
        acc = acc.checked_mul(10)?;
        if is_negative {
            acc = acc.checked_sub(digit)?;
        } else {
            acc = acc.checked_add(digit)?;
        }
    }
    Some(acc)
}

fn serial_write_signed_decimal(value: i64) {
    if value < 0 {
        serial_write(b"-");
        let magnitude = (-(value as i128)) as u64;
        serial_write_word(magnitude);
    } else {
        serial_write_word(value as u64);
    }
}

fn bytes_eq(left: &[u8], right: &[u8]) -> bool {
    left.len() == right.len() && left.iter().zip(right).all(|(a, b)| a == b)
}

#[allow(dead_code)]
fn serial_write_hex(value: u64) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for i in (0..16).rev() {
        let nibble = ((value >> (i * 4)) & 0xf) as usize;
        unsafe { outb(COM1, HEX[nibble]) };
    }
}

fn serial_has_input() -> bool {
    unsafe { inb(COM1 + 5) & 1 != 0 }
}

fn serial_write_decimal(mut value: u32) {
    let mut digits = [0_u8; 10];
    let mut cursor = digits.len();
    if value == 0 {
        serial_write(b"0");
        return;
    }
    while value != 0 && cursor > 0 {
        cursor -= 1;
        unsafe {
            *digits.get_unchecked_mut(cursor) = b'0' + (value % 10) as u8;
        }
        value /= 10;
    }
    serial_write(unsafe {
        core::slice::from_raw_parts(digits.as_ptr().add(cursor), digits.len() - cursor)
    });
}

fn qemu_exit(code: u32) -> ! {
    unsafe {
        asm!("out dx, eax", in("dx") 0xf4_u16, in("eax") code, options(nomem, nostack));
    }
    loop {
        core::hint::spin_loop();
    }
}

unsafe fn outb(port: u16, value: u8) {
    asm!("out dx, al", in("dx") port, in("al") value, options(nomem, nostack));
}

unsafe fn inb(port: u16) -> u8 {
    let value: u8;
    asm!("in al, dx", in("dx") port, out("al") value, options(nomem, nostack));
    value
}

unsafe fn outl(port: u16, value: u32) {
    asm!("out dx, eax", in("dx") port, in("eax") value, options(nomem, nostack));
}

unsafe fn inl(port: u16) -> u32 {
    let value: u32;
    asm!("in eax, dx", in("dx") port, out("eax") value, options(nomem, nostack));
    value
}
