#![no_std]
#![no_main]

use bootloader_api::{entry_point, BootInfo};
use core::arch::asm;
use core::mem::MaybeUninit;
use core::panic::PanicInfo;
use wsm_os_runtime::{ConsCell, RuntimeContext};
use wsm_os_target::{decode_symbol, Word};

entry_point!(kernel_main);

fn kernel_main(_boot_info: &'static mut BootInfo) -> ! {
    serial_init();
    serial_write(b"WSM-OS BOOT schema=1 arch=x86_64 status=ok\n");

    let heap = core::ptr::addr_of_mut!(HEAP).cast::<MaybeUninit<ConsCell>>();
    // SAFETY: HEAP is a private, aligned, fixed-size arena used only by this
    // single-threaded boot witness for the lifetime of the context.
    let mut context = unsafe { RuntimeContext::new(heap, HEAP_CAPACITY, kernel_failure) };
    // SAFETY: fixture.o is generated by the pinned CML revision, its committed
    // manifest exports exactly wsm_entry and admits only the wsm_* ABI imports.
    let result = unsafe { wsm_entry(&mut context) };

    if is_first_fixture_result(result, &context) {
        serial_write(b"WSM-OS RESULT schema=1 value=(A . B) status=ok\n");
        qemu_exit(0x10)
    } else {
        serial_write(b"WSM-OS RESULT schema=1 error=abi-violation status=error\n");
        qemu_exit(0x12)
    }
}

const HEAP_CAPACITY: usize = 8;
static mut HEAP: [MaybeUninit<ConsCell>; HEAP_CAPACITY] = [MaybeUninit::uninit(); HEAP_CAPACITY];

unsafe extern "C" {
    fn wsm_entry(context: *mut RuntimeContext) -> Word;
}

extern "C" fn kernel_failure(code: u32) -> ! {
    serial_write(b"WSM-OS RESULT schema=1 error=runtime-failure code=");
    serial_write_decimal(code);
    serial_write(b" status=error\n");
    qemu_exit(0x12)
}

fn is_first_fixture_result(value: Word, context: &RuntimeContext) -> bool {
    let Ok(cell) = context.cell(value) else {
        return false;
    };
    decode_symbol(cell.car) == Some(1) && decode_symbol(cell.cdr) == Some(2)
}

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    serial_init();
    serial_write(b"WSM-OS PANIC schema=1 arch=x86_64 status=panic\n");
    qemu_exit(0x11)
}

const COM1: u16 = 0x3f8;

fn serial_init() {
    unsafe {
        outb(COM1 + 1, 0x00);
        outb(COM1 + 3, 0x80);
        outb(COM1, 0x03);
        outb(COM1 + 1, 0x00);
        outb(COM1 + 3, 0x03);
        outb(COM1 + 2, 0xc7);
        outb(COM1 + 4, 0x0b);
    }
}

fn serial_write(bytes: &[u8]) {
    for &byte in bytes {
        unsafe { outb(COM1, byte) };
    }
}

fn serial_write_decimal(mut value: u32) {
    let mut digits = [0_u8; 10];
    let mut cursor = digits.len();
    if value == 0 {
        serial_write(b"0");
        return;
    }
    while value != 0 {
        cursor -= 1;
        digits[cursor] = b'0' + (value % 10) as u8;
        value /= 10;
    }
    serial_write(&digits[cursor..]);
}

fn qemu_exit(code: u32) -> ! {
    unsafe {
        asm!("out dx, eax", in("dx") 0xf4_u16, in("eax") code, options(nomem, nostack));
    }
    loop {
        core::hint::spin_loop();
    }
}

unsafe fn outb(port: u16, value: u8) {
    asm!("out dx, al", in("dx") port, in("al") value, options(nomem, nostack));
}
